### ISSUE TITLE
[Question] Package as hud mod?

### ISSUE THREAD

**Issue by TDarkShadow** [CriticalFlaw/TF2-HUD-Fix#10]
Would it be possible to package these fixes as a HUD mod until Valve implements these fixes?
I prefer the default HUD and I would very like to play with these fixes.

**Comment by CriticalFlaw** [comment]
HUDs don't need to be packaged as a vpk mod to work in game. Just download the repo, extract it into your tf/custom folder.

This project already comes with a info.vdf file so it will work out of the box.

**Comment by TDarkShadow** [comment]
Aah, that's why I've been doing wrong.
I removed the vdf file, because I assumed it was something like the readme file.
Thank you so much!
