### ISSUE TITLE
Achievement tracker overlaps the mini sentry status in MVM

### ISSUE THREAD

**Issue by Scoutman01** [CriticalFlaw/TF2-HUD-Fix#12]
![Sans titre 1](https://user-images.githubusercontent.com/50184129/100653163-45676d00-3348-11eb-8bc3-a8c744938a00.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/TF2-HUD-Fix/commit/8cfdcde235a69436134805e94c1dbc249247b836. Thank you for reporting.
